Repository CanalTP/NavitiaSDKUX_ios, pull requests merged in 2018-11, with the labels that each got.

#211 ✨ [SDK-437] - Update code error for masabi 📜
  NavitiaSDKUI.xcodeproj/project.pbxproj
  NavitiaSDKUI/Lib/NavitiaSDKPartners/Account/KeolisAccountManagement/KeolisAccountManagement.swift
  NavitiaSDKUI/Lib/NavitiaSDKPartners/Book/VSCTBookManagement/VSCTBookManagement.swift
  NavitiaSDKUI/Lib/NavitiaSDKPartners/Ticket/MasabiTicketManagement/MasabiTicketManagement.swift
  NavitiaSDKUI/Lib/NavitiaSDKPartners/Utils/NavitiaSDKPartnersReturnCodes.swift
  NavitiaSDKUI/UI/Ticket/TicketViewController.swift
  Podfile
  Podfile.lock
Labels: QA VALIDATION 😈

#213 ✨ [SDK-548] - Update Readme
  NavitiaSDKUI/UI/JourneySolutionRoadmap/JourneySolutionRoadmapViewController.swift
  README.md
Labels: MERGE AUTHORIZED 💪

#215 ✨ [SDK-521] - Swift 4.2
  .swift-version
  Example/NavitiaSDKUI-Example.xcodeproj/project.pbxproj
  Example/NavitiaSDKUI-Example/AppDelegate.swift
  Example/NavitiaSDKUI-Example/ViewController.swift
  Example/Podfile.lock
  NavitiaSDKUI.xcodeproj/project.pbxproj
  NavitiaSDKUI.xcodeproj/xcshareddata/xcschemes/NavitiaSDKUI.xcscheme
  NavitiaSDKUI.xcodeproj/xcshareddata/xcschemes/NavitiaSDKUITests.xcscheme
  NavitiaSDKUI/Framedation/Extension/Disruption+Extension.swift
  NavitiaSDKUI/Framedation/Extension/UIViewController+Extension.swift
  NavitiaSDKUI/Framedation/Helper/NavitiaSDKUserDefaultsManager.swift
  NavitiaSDKUI/Lib/Checkbox.swift
  NavitiaSDKUI/Lib/FloatRatingView.swift
  NavitiaSDKUI/Lib/NavitiaSDK/Frameworks/Alamofire/Request.swift
  NavitiaSDKUI/Lib/NavitiaSDK/Frameworks/Alamofire/ResponseSerialization.swift
  NavitiaSDKUI/Lib/NavitiaSDK/Frameworks/Alamofire/ServerTrustPolicy.swift
  NavitiaSDKUI/Lib/NavitiaSDK/Frameworks/Alamofire/SessionManager.swift
  NavitiaSDKUI/Lib/NavitiaSDK/Frameworks/Alamofire/TaskDelegate.swift
  NavitiaSDKUI/Lib/NavitiaSDK/NavitiaConfiguration.swift
  NavitiaSDKUI/Lib/NavitiaSDK/Swaggers/APIs.swift
  NavitiaSDKUI/Lib/NavitiaSDK/Swaggers/Models.swift
  NavitiaSDKUI/Scenes/Common/AlertViewController.swift
  NavitiaSDKUI/Scenes/ListJourneys/ListJourneysViewController.swift
  NavitiaSDKUI/Scenes/ListRidesharingOffers/View/RidesharingOfferCollectionViewCell.swift
  NavitiaSDKUI/Scenes/ShowJourneyRoadmap/ShowJourneyRoadmapPresenter.swift
  NavitiaSDKUI/Scenes/ShowJourneyRoadmap/ShowJourneyRoadmapViewController.swift
  NavitiaSDKUI/Scenes/ShowJourneyRoadmap/View/OnDemandItemView.swift
  NavitiaSDKUI/Scenes/ShowJourneyRoadmap/View/RidesharingView.swift
Labels: MERGE AUTHORIZED 💪

#218 ✨ [SDK-560] - Add direct path parameter 🔌
  NavitiaSDKUI/Framedation/Models/JourneysRequest.swift
  NavitiaSDKUI/Workers/NavitiaWorker.swift
  README.md
Labels: MERGE AUTHORIZED 💪

#219 🐛 [SDK-576] - Fix bug
  NavitiaSDKUI/Scenes/ListJourneys/Interface/JourneySolutionCollectionViewCell.xib
  NavitiaSDKUI/Scenes/ShowJourneyRoadmap/View/EmissionView.swift
Labels: MERGE AUTHORIZED 💪

#214 ✨ [SDK-509] - Enable BSS States 🚲
  NavitiaSDKUI/Scenes/ShowJourneyRoadmap/Interface/StepView.xib
  NavitiaSDKUI/Scenes/ShowJourneyRoadmap/ShowJourneyRoadmapModels.swift
  NavitiaSDKUI/Scenes/ShowJourneyRoadmap/ShowJourneyRoadmapPresenter.swift
  NavitiaSDKUI/Scenes/ShowJourneyRoadmap/ShowJourneyRoadmapViewController.swift
  NavitiaSDKUI/Scenes/ShowJourneyRoadmap/View/StepView.swift
Labels: MERGE AUTHORIZED 💪

#220 🐛 [SDK-579] - Fix color in public transport view 💄
  NavitiaSDKUI/Scenes/ShowJourneyRoadmap/View/PublicTransportStepView.swift
Labels: MERGE AUTHORIZED 💪

#227 🐛[SDK-583] - Fix bug with roadmap
  NavitiaSDKUI/Scenes/Common/StackScrollView.swift
Labels: REVIEW REQUIRED! 👀

#226 🎉 [SDK-559] - Improvement
  NavitiaSDKUI.xcodeproj/project.pbxproj
  NavitiaSDKUI/Framedation/Extension/Disruption+Extension.swift
  NavitiaSDKUI/Framedation/Extension/Int32+Extension.swift
  NavitiaSDKUI/Framedation/Extension/Message+Extension.swift
  NavitiaSDKUI/Framedation/Extension/StackView+Extension.swift
  NavitiaSDKUI/Framedation/Extension/String+Extension.swift
  NavitiaSDKUI/Framedation/Extension/UIColor+Extension.swift
  NavitiaSDKUI/Framedation/Extension/UIFont+Extension.swift
  NavitiaSDKUI/Framedation/Extension/UIImageView+Extension.swift
  NavitiaSDKUI/Framedation/Extension/UIView+Extension.swift
  NavitiaSDKUI/Framedation/Extension/UIViewController+Extension.swift
  NavitiaSDKUI/Framedation/Helper/NavitiaSDKUserDefaultsManager.swift
  NavitiaSDKUI/Framedation/Helper/TransportHelper.swift
  NavitiaSDKUI/Scenes/Common/CustomAnnotation.swift
  NavitiaSDKUI/Scenes/ListJourneys/ListJourneysPresenter.swift
  NavitiaSDKUI/Scenes/ListJourneys/ListJourneysViewController.swift
  NavitiaSDKUI/Scenes/ListJourneys/View/JourneyEmptySolutionCollectionViewCell.swift
  NavitiaSDKUI/Scenes/ListJourneys/View/RidesharingInformationCollectionViewCell.swift
  NavitiaSDKUI/Scenes/ListRidesharingOffers/ListRidesharingOffersPresenter.swift
  NavitiaSDKUI/Scenes/ListRidesharingOffers/ListRidesharingOffersViewController.swift
  NavitiaSDKUI/Scenes/ListRidesharingOffers/View/RidesharingOfferCollectionViewCell.swift
  NavitiaSDKUI/Scenes/ShowJourneyRoadmap/ShowJourneyRoadmapModels.swift
  NavitiaSDKUI/Scenes/ShowJourneyRoadmap/ShowJourneyRoadmapPresenter.swift
  NavitiaSDKUI/Scenes/ShowJourneyRoadmap/ShowJourneyRoadmapViewController.swift
  NavitiaSDKUI/Scenes/ShowJourneyRoadmap/View/DepartureArrivalStepView.swift
  NavitiaSDKUI/Scenes/ShowJourneyRoadmap/View/EmissionView.swift
  NavitiaSDKUI/Scenes/ShowJourneyRoadmap/View/JourneySolutionView.swift
  NavitiaSDKUI/Scenes/ShowJourneyRoadmap/View/OnDemandItemView.swift
  NavitiaSDKUI/Scenes/ShowJourneyRoadmap/View/PublicTransportStepView.swift
  NavitiaSDKUI/Scenes/ShowJourneyRoadmap/View/RidesharingView.swift
  NavitiaSDKUI/Scenes/ShowJourneyRoadmap/View/StepView.swift
  NavitiaSDKUITests/Scenes/ListRidesharingOffers/ListRidesharingOffersPresenterTests.swift
  NavitiaSDKUITests/Scenes/ShowJourneyRoadmap/ShowJourneyRoadmapPresenterTests.swift
Labels: MERGE AUTHORIZED 💪
