Repository CanalTP/NavitiaSDKUX_ios, pull requests merged in 2019-10, with the labels that each got.

#307 Fix UI bug frieze overlapping walking information
  NavitiaSDKUI/Scenes/ListJourneys/Interface/JourneySolutionCollectionViewCell.xib
  NavitiaSDKUI/Scenes/ListJourneys/ListJourneysViewController.swift
Labels: REVIEW IN PROGRESS ⏱

#306 Update PricedTicket
  NavitiaSDKUI.xcodeproj/project.pbxproj
  NavitiaSDKUI/Framedation/Models/PricedTicket.swift
  NavitiaSDKUI/Scenes/ListJourneys/ListJourneysPresenter.swift
  NavitiaSDKUI/Scenes/ListJourneys/ListJourneysViewController.swift
  NavitiaSDKUI/Scenes/ShowJourneyRoadmap/Interface/BuyTicketButtonView.xib
  NavitiaSDKUI/Scenes/ShowJourneyRoadmap/MaasJourney.swift
  NavitiaSDKUI/Scenes/ShowJourneyRoadmap/ShowJourneyRoadmapInteractor.swift
  NavitiaSDKUI/Scenes/ShowJourneyRoadmap/ShowJourneyRoadmapViewController.swift
  NavitiaSDKUI/Scenes/ShowJourneyRoadmap/View/PublicTransportStepView.swift
Labels: MERGE AUTHORIZED 💪

#305 ✅ Summary redirect to Upcoming journeys
  NavitiaSDKUI/NavitiaSDKUIConfig.swift
  NavitiaSDKUI/Scenes/FormJourney/FormJourneyInteractor.swift
  NavitiaSDKUI/Scenes/FormJourney/FormJourneyViewController.swift
  NavitiaSDKUI/Scenes/ListJourneys/ListJourneysInteractor.swift
  NavitiaSDKUI/Scenes/ListJourneys/ListJourneysViewController.swift
  NavitiaSDKUI/Scenes/ShowJourneyRoadmap/ShowJourneyRoadmapViewController.swift
Labels: MERGE AUTHORIZED 💪

#309 ✨ Redirecting to upcoming journeys
  NavitiaSDKUI/NavitiaSDKUIConfig.swift
  NavitiaSDKUI/Scenes/Common/TicketPriceView.swift
  NavitiaSDKUI/Scenes/FormJourney/FormJourneyInteractor.swift
  NavitiaSDKUI/Scenes/FormJourney/FormJourneyViewController.swift
  NavitiaSDKUI/Scenes/ListJourneys/ListJourneysInteractor.swift
  NavitiaSDKUI/Scenes/ListJourneys/ListJourneysRouter.swift
  NavitiaSDKUI/Scenes/ListJourneys/ListJourneysViewController.swift
  NavitiaSDKUI/Scenes/ShowJourneyRoadmap/ShowJourneyRoadmapViewController.swift
Labels: MERGE AUTHORIZED 💪

#310 🐛 Fix prices bugs
  NavitiaSDKUI/Scenes/FormJourney/FormJourneyInteractor.swift
  NavitiaSDKUI/Scenes/FormJourney/FormJourneyRouter.swift
  NavitiaSDKUI/Scenes/FormJourney/FormJourneyViewController.swift
  NavitiaSDKUI/Scenes/ListJourneys/ListJourneysInteractor.swift
  NavitiaSDKUI/Scenes/ListJourneys/ListJourneysRouter.swift
  NavitiaSDKUI/Scenes/ListJourneys/ListJourneysViewController.swift
  NavitiaSDKUI/Scenes/ShowJourneyRoadmap/ShowJourneyRoadmapInteractor.swift
  NavitiaSDKUI/Scenes/ShowJourneyRoadmap/ShowJourneyRoadmapModels.swift
  NavitiaSDKUI/Scenes/ShowJourneyRoadmap/ShowJourneyRoadmapPresenter.swift
  NavitiaSDKUI/Scenes/ShowJourneyRoadmap/ShowJourneyRoadmapViewController.swift
  NavitiaSDKUITests/Scenes/ShowJourneyRoadmap/ShowJourneyRoadmapPresenterTests.swift
Labels: REVIEW REQUIRED! 👀

#311 🐛 Add Exception for taxi mode to show its label
  NavitiaSDKUI/Scenes/Common/Frieze/FriezePresenter.swift
Labels: REVIEW REQUIRED! 👀

#312 Fix taxi price display
  NavitiaSDKUI/Scenes/ListJourneys/ListJourneysPresenter.swift
Labels: MERGE AUTHORIZED 💪

#314 Fix departure/arrival color in roadmap
  NavitiaSDKUI/Scenes/ShowJourneyRoadmap/View/DepartureArrivalStepView.swift
Labels: MERGE AUTHORIZED 💪

#313 Fix/traveler type bad display
  NavitiaSDKUI/Scenes/Common/CustomAnnotation.swift
  NavitiaSDKUI/Scenes/Common/SearchView.swift
  NavitiaSDKUI/Scenes/FormJourney/FormJourneyViewController.swift
  NavitiaSDKUI/Scenes/ListJourneys/ListJourneysViewController.swift
  NavitiaSDKUI/Scenes/ShowJourneyRoadmap/Interface/PublicTransportStepView.xib
  NavitiaSDKUI/Scenes/ShowJourneyRoadmap/ShowJourneyRoadmapInteractor.swift
  NavitiaSDKUI/Scenes/ShowJourneyRoadmap/ShowJourneyRoadmapViewController.swift
  NavitiaSDKUI/Storyboard/Journey.storyboard
Labels: MERGE AUTHORIZED 💪

#315 🐛 Change departure/arrival icons
  NavitiaSDKUI/Resources/Images.xcassets/journey_arrival_pin.imageset/Contents.json
  NavitiaSDKUI/Resources/Images.xcassets/journey_arrival_pin.imageset/arrival.pdf
  NavitiaSDKUI/Resources/Images.xcassets/journey_departure_pin.imageset/Contents.json
  NavitiaSDKUI/Resources/Images.xcassets/journey_departure_pin.imageset/departure.pdf
  NavitiaSDKUI/Scenes/Common/CustomAnnotation.swift
Labels: MERGE AUTHORIZED 💪

#316 🐛 Fix ticket error icon default visibility
  NavitiaSDKUI/Scenes/ShowJourneyRoadmap/Interface/PublicTransportStepView.xib
Labels: REVIEW REQUIRED! 👀

#317 💄 Remove default values in labels for TicketPriceView
  NavitiaSDKUI/Scenes/Common/Interface/TicketPriceView.xib
  ci/Build
Labels: MERGE AUTHORIZED 💪

#319 ⚡️ Update localized strings
  NavitiaSDKUI/Framedation/Extension/Int32+Extension.swift
  NavitiaSDKUI/Resources/en.lproj/Localizable.strings
  NavitiaSDKUI/Resources/fr.lproj/Localizable.strings
  NavitiaSDKUI/Resources/nl-NL.lproj/Localizable.strings
  NavitiaSDKUI/Resources/nl.lproj/Localizable.strings
  NavitiaSDKUI/Scenes/Common/Interface/WalkingSpeedView.xib
  NavitiaSDKUI/Scenes/Common/WalkingSpeedView.swift
  NavitiaSDKUI/Scenes/ShowJourneyRoadmap/Interface/PublicTransportStepView.xib
  NavitiaSDKUI/Scenes/ShowJourneyRoadmap/View/PublicTransportStepView.swift
Labels: MERGE AUTHORIZED 💪

#318 fix single search mode
  NavitiaSDKUI/Scenes/Common/SearchView.swift
  NavitiaSDKUI/Scenes/ListPlaces/ListPlacesInteractor.swift
  NavitiaSDKUI/Scenes/ListPlaces/ListPlacesViewController.swift
Labels: MERGE AUTHORIZED 💪

#321 Fix empty cancel search
  NavitiaSDKUI/Scenes/ListJourneys/ListJourneysViewController.swift
Labels: MERGE AUTHORIZED 💪

#320 Fix list places selection
  NavitiaSDKUI/Framedation/Extension/UIViewController+Extension.swift
  NavitiaSDKUI/Scenes/ListPlaces/ListPlacesViewController.swift
Labels: MERGE AUTHORIZED 💪

#322 🐛 Make all models optional for Maas tickets
  NavitiaSDKUI/Scenes/ShowJourneyRoadmap/MaasTicket.swift
Labels: REVIEW REQUIRED! 👀

#323 ⚡️ Adding timestamp to avoid wrong prices, fix ticket not available n…
  NavitiaSDKUI/Resources/Images.xcassets/ticket.imageset/ticket.pdf
  NavitiaSDKUI/Resources/Images.xcassets/ticket_not_available.imageset/Contents.json
  NavitiaSDKUI/Resources/Images.xcassets/ticket_not_available.imageset/ticket barre.pdf
  NavitiaSDKUI/Resources/Images.xcassets/ticket_not_available.imageset/ticket_unavailable.pdf
  NavitiaSDKUI/Scenes/Common/Interface/TicketPriceView.xib
  NavitiaSDKUI/Scenes/Common/TicketPriceView.swift
  NavitiaSDKUI/Scenes/ListJourneys/ListJourneysViewController.swift
  NavitiaSDKUI/Scenes/ListJourneys/View/JourneySolutionCollectionViewCell.swift
  NavitiaSDKUI/Scenes/ShowJourneyRoadmap/Interface/PublicTransportStepView.xib
  NavitiaSDKUI/Scenes/ShowJourneyRoadmap/View/PublicTransportStepView.swift
Labels: REVIEW REQUIRED! 👀

#324 Fix datetime in searchview
  NavitiaSDKUI/Scenes/Common/Interface/SearchView.xib
  NavitiaSDKUI/Scenes/FormJourney/FormJourneyModels.swift
  NavitiaSDKUI/Scenes/ListJourneys/ListJourneysInteractor.swift
  NavitiaSDKUI/Scenes/ListJourneys/ListJourneysPresenter.swift
  NavitiaSDKUI/Scenes/ListJourneys/ListJourneysViewController.swift
  NavitiaSDKUITests/Scenes/ListJourneys/ListJourneysInteractorTests.swift
  NavitiaSDKUITests/Scenes/ListJourneys/ListJourneysPresenterTests.swift
Labels: CHANGES MADE 😎

#327 🐛 Fix "now" time
  NavitiaSDKUI/Scenes/FormJourney/FormJourneyViewController.swift
  NavitiaSDKUI/Scenes/FormJourney/View/DateFormView.swift
Labels: MERGE AUTHORIZED 💪

#328 🐛 Fix buy ticket button font
  NavitiaSDKUI/Scenes/ShowJourneyRoadmap/View/BuyTicketButtonView.swift
Labels: MERGE AUTHORIZED 💪

#329 🐛 Remove bike from section modes if wheelchair is enabled
  NavitiaSDKUI/Workers/NavitiaWorker.swift
Labels: MERGE AUTHORIZED 💪

#331 Fix favorite request
  NavitiaSDKUI/Scenes/ListJourneys/ListJourneysInteractor.swift
  NavitiaSDKUI/Scenes/ListJourneys/ListJourneysPresenter.swift
  NavitiaSDKUI/Scenes/ListJourneys/ListJourneysViewController.swift
  NavitiaSDKUI/Scenes/ListPlaces/ListPlacesViewController.swift
Labels: MERGE AUTHORIZED 💪

#330 🎨 Descending order for showing history autocomplete items
  NavitiaSDKUI/Workers/DataBaseWorker.swift
Labels: MERGE AUTHORIZED 💪

#332 Fix "minute" text in roadmap
  NavitiaSDKUI/Resources/en.lproj/Localizable.strings
  NavitiaSDKUI/Resources/fr.lproj/Localizable.strings
  NavitiaSDKUI/Resources/nl.lproj/Localizable.strings
  NavitiaSDKUI/Scenes/ShowJourneyRoadmap/ShowJourneyRoadmapPresenter.swift
  NavitiaSDKUITests/Scenes/ShowJourneyRoadmap/ShowJourneyRoadmapPresenterTests.swift
Labels: MERGE AUTHORIZED 💪

#335 Fix price unavailable display
  NavitiaSDKUI/Scenes/Common/Frieze/FriezePresenter.swift
  NavitiaSDKUI/Scenes/Common/Interface/TicketPriceView.xib
  NavitiaSDKUI/Scenes/Common/SearchView.swift
  NavitiaSDKUI/Scenes/ListJourneys/View/JourneySolutionCollectionViewCell.swift
  NavitiaSDKUI/Scenes/ListPlaces/ListPlacesViewController.swift
  NavitiaSDKUI/Scenes/ShowJourneyRoadmap/Interface/JourneySolutionView.xib
  NavitiaSDKUI/Scenes/ShowJourneyRoadmap/ShowJourneyRoadmapPresenter.swift
  NavitiaSDKUI/Scenes/ShowJourneyRoadmap/View/JourneySolutionView.swift
Labels: MERGE AUTHORIZED 💪

#337 Update loco
  NavitiaSDKUI/Resources/en.lproj/Localizable.strings
  NavitiaSDKUI/Resources/fr.lproj/Localizable.strings
  NavitiaSDKUI/Resources/nl.lproj/Localizable.strings
Labels: MERGE AUTHORIZED 💪
