Repository CanalTP/NavitiaSDKUX_ios, pull requests merged in 2019-09, with the labels that each got.

#288 🐛 Fix navigation title
  NavitiaSDKUI/Framedation/Extension/UIViewController+Extension.swift
Labels: REVIEW REQUIRED! 👀

#289 🐛 Fix stations and stops section title
  NavitiaSDKUI/Resources/en.lproj/Localizable.strings
  NavitiaSDKUI/Resources/fr.lproj/Localizable.strings
  NavitiaSDKUI/Scenes/ListPlaces/ListPlacesPresenter.swift
Labels: MERGE AUTHORIZED 💪

#290 Feature/sdk 1149
  NavitiaSDKUI/Framedation/Models/AutocompletionHistory.swift
  NavitiaSDKUI/Scenes/Common/Interface/SearchView.xib
  NavitiaSDKUI/Scenes/Common/SearchView.swift
  NavitiaSDKUI/Scenes/ListJourneys/ListJourneysViewController.swift
  NavitiaSDKUI/Scenes/ListPlaces/ListPlacesInteractor.swift
  NavitiaSDKUI/Scenes/ListPlaces/ListPlacesViewController.swift
  NavitiaSDKUI/Storyboard/Journey.storyboard
Labels: MERGE AUTHORIZED 💪

#291 display my position row even if location is disabled.
  NavitiaSDKUI.xcodeproj/project.pbxproj
  NavitiaSDKUI/Framedation/Extension/UITableView+Extension.swift
  NavitiaSDKUI/Resources/en.lproj/Localizable.strings
  NavitiaSDKUI/Resources/fr.lproj/Localizable.strings
  NavitiaSDKUI/Scenes/ListPlaces/ListPlacesModels.swift
  NavitiaSDKUI/Scenes/ListPlaces/ListPlacesViewController.swift
  NavitiaSDKUI/Scenes/ListPlaces/View/PlacesTableViewCell.swift
Labels: CHANGES MADE 😎

#296 Fix the click on solution in ListJourneyViewController
  NavitiaSDKUI/Scenes/ListJourneys/ListJourneysRouter.swift
  NavitiaSDKUI/Scenes/ListPlaces/ListPlacesInteractor.swift
Labels: MERGE AUTHORIZED 💪

#298 add new param to SDK configuration to use advanced search mode in Lis…
  NavitiaSDKUI/NavitiaSDKUIConfig.swift
  NavitiaSDKUI/Scenes/Common/SearchView.swift
  NavitiaSDKUI/Scenes/FormJourney/FormJourneyRouter.swift
  NavitiaSDKUI/Scenes/ListJourneys/ListJourneysViewController.swift
Labels: MERGE AUTHORIZED 💪

#299 🐛 Fix navigation controller item tint color
  NavitiaSDKUI/Framedation/Extension/UIViewController+Extension.swift
Labels: REVIEW REQUIRED! 👀

#297 Feature/sdk 1176
  NavitiaSDKUI.xcodeproj/project.pbxproj
  NavitiaSDKUI/Framedation/Models/JourneysRequest.swift
  NavitiaSDKUI/Resources/Images.xcassets/fast-walking.imageset/Contents.json
  NavitiaSDKUI/Resources/Images.xcassets/fast-walking.imageset/fast-walking.pdf
  NavitiaSDKUI/Resources/Images.xcassets/luggage.imageset/Contents.json
  NavitiaSDKUI/Resources/Images.xcassets/luggage.imageset/Valise.pdf
  NavitiaSDKUI/Resources/Images.xcassets/normal-walking.imageset/Contents.json
  NavitiaSDKUI/Resources/Images.xcassets/normal-walking.imageset/normal-walking.pdf
  NavitiaSDKUI/Resources/Images.xcassets/slow-walking.imageset/Contents.json
  NavitiaSDKUI/Resources/Images.xcassets/slow-walking.imageset/slow-walking.pdf
  NavitiaSDKUI/Resources/Images.xcassets/wheelchair.imageset/Contents.json
  NavitiaSDKUI/Resources/Images.xcassets/wheelchair.imageset/wheelchair.pdf
  NavitiaSDKUI/Resources/en.lproj/Localizable.strings
  NavitiaSDKUI/Resources/fr.lproj/Localizable.strings
  NavitiaSDKUI/Resources/nl-NL.lproj/Localizable.strings
  NavitiaSDKUI/Scenes/Common/Interface/SubtitleView.xib
  NavitiaSDKUI/Scenes/Common/Interface/TravelerTypeView.xib
  NavitiaSDKUI/Scenes/Common/Interface/WalkingSpeedView.xib
  NavitiaSDKUI/Scenes/Common/SearchView.swift
  NavitiaSDKUI/Scenes/Common/SubtitleView.swift
  NavitiaSDKUI/Scenes/Common/TravelerTypeView.swift
  NavitiaSDKUI/Scenes/Common/WalkingSpeedView.swift
  NavitiaSDKUI/Scenes/FormJourney/FormJourneyViewController.swift
  NavitiaSDKUI/Scenes/FormJourney/Interface/ModeTransportView.xib
  NavitiaSDKUI/Scenes/ListJourneys/ListJourneysViewController.swift
  NavitiaSDKUI/Workers/NavitiaWorker.swift
Labels: CHANGES MADE 😎

#300 🐛 Fix icons missing
  NavitiaSDKUI/Resources/Images.xcassets/Transport Modes/journey_mode_bus-tad.imageset/Contents.json
  NavitiaSDKUI/Resources/Images.xcassets/Transport Modes/journey_mode_bus-tad.imageset/bus-tad.pdf
  NavitiaSDKUI/Resources/Images.xcassets/Transport Modes/journey_mode_car-tad.imageset/Contents.json
  NavitiaSDKUI/Resources/Images.xcassets/Transport Modes/journey_mode_car-tad.imageset/car-tad.pdf
  NavitiaSDKUI/Resources/Images.xcassets/Transport Modes/journey_mode_taxi-tad.imageset/Contents.json
  NavitiaSDKUI/Resources/Images.xcassets/Transport Modes/journey_mode_taxi-tad.imageset/taxi-tad.pdf
  NavitiaSDKUI/Scenes/Common/Interface/FriezeSectionView.xib
  NavitiaSDKUI/Scenes/Common/Interface/SearchView.xib
Labels: MERGE AUTHORIZED 💪

#294 Feature/sdk 1173
  Example/NavitiaSDKUI-Example.xcodeproj/project.pbxproj
  Example/NavitiaSDKUI-Example/ConfigurationViewController.swift
  NavitiaSDKUI.xcodeproj/project.pbxproj
  NavitiaSDKUI/Framedation/Models/PricedTicket.swift
  NavitiaSDKUI/Framedation/Models/TicketInput.swift
  NavitiaSDKUI/Lib/NavitiaSDK/Apis/JourneysApi.swift
  NavitiaSDKUI/Lib/NavitiaSDK/Models/Journey.swift
  NavitiaSDKUI/NavitiaSDKUIConfig.swift
  NavitiaSDKUI/Scenes/Common/Frieze/FriezePresenter.swift
  NavitiaSDKUI/Scenes/Common/Frieze/FriezeSectionView.swift
  NavitiaSDKUI/Scenes/Common/Frieze/FriezeView.swift
  NavitiaSDKUI/Scenes/Common/Interface/FriezeSectionView.xib
  NavitiaSDKUI/Scenes/FormJourney/FormJourneyInteractor.swift
  NavitiaSDKUI/Scenes/FormJourney/FormJourneyRouter.swift
  NavitiaSDKUI/Scenes/FormJourney/FormJourneyViewController.swift
  NavitiaSDKUI/Scenes/FormJourney/View/TransportModeView.swift
  NavitiaSDKUI/Scenes/ListJourneys/Interface/JourneySolutionCollectionViewCell.xib
  NavitiaSDKUI/Scenes/ListJourneys/Interface/JourneySolutionLoadCollectionViewCell.xib
  NavitiaSDKUI/Scenes/ListJourneys/ListJourneysInteractor.swift
  NavitiaSDKUI/Scenes/ListJourneys/ListJourneysModels.swift
  NavitiaSDKUI/Scenes/ListJourneys/ListJourneysPresenter.swift
  NavitiaSDKUI/Scenes/ListJourneys/ListJourneysViewController.swift
  NavitiaSDKUI/Scenes/ListJourneys/View/JourneySolutionCollectionViewCell.swift
  NavitiaSDKUI/Scenes/ShowJourneyRoadmap/View/JourneySolutionView.swift
  NavitiaSDKUI/Workers/NavitiaWorker.swift
  NavitiaSDKUITests/Scenes/ListJourneys/ListJourneysInteractorTests.swift
  NavitiaSDKUITests/Scenes/ListJourneys/ListJourneysPresenterTests.swift
  NavitiaSDKUITests/Workers/NavitiaWorkersTests.swift
Labels: MERGE AUTHORIZED 💪

#301 🐛 Fix missing icons
  NavitiaSDKUI/Resources/Images.xcassets/Transport Modes/journey_mode_localtrain.imageset/Contents.json
  NavitiaSDKUI/Resources/Images.xcassets/Transport Modes/journey_mode_localtrain.imageset/train.pdf
  NavitiaSDKUI/Scenes/ShowJourneyRoadmap/View/PublicTransportStepView.swift
Labels: MERGE AUTHORIZED 💪

#302 Fix/loading price tickets
  NavitiaSDKUI.xcodeproj/project.pbxproj
  NavitiaSDKUI/Framedation/Models/PricesModel.swift
  NavitiaSDKUI/NavitiaSDKUIConfig.swift
  NavitiaSDKUI/Scenes/FormJourney/FormJourneyViewController.swift
  NavitiaSDKUI/Scenes/ListJourneys/ListJourneysModels.swift
  NavitiaSDKUI/Scenes/ListJourneys/ListJourneysPresenter.swift
  NavitiaSDKUI/Scenes/ListJourneys/ListJourneysViewController.swift
  NavitiaSDKUI/Scenes/ListJourneys/View/JourneySolutionCollectionViewCell.swift
Labels: MERGE AUTHORIZED 💪

#303 🎨 Update sent Maas order models
  NavitiaSDKUI.xcodeproj/project.pbxproj
  NavitiaSDKUI/Scenes/ShowJourneyRoadmap/MaasOrder.swift
  NavitiaSDKUI/Scenes/ShowJourneyRoadmap/MaasTicket.swift
  NavitiaSDKUI/Scenes/ShowJourneyRoadmap/ShowJourneyRoadmapInteractor.swift
  NavitiaSDKUI/Scenes/ShowJourneyRoadmap/ShowJourneyRoadmapModels.swift
  NavitiaSDKUI/Scenes/ShowJourneyRoadmap/ShowJourneyRoadmapPresenter.swift
  NavitiaSDKUI/Scenes/ShowJourneyRoadmap/ShowJourneyRoadmapViewController.swift
  NavitiaSDKUI/Scenes/ShowJourneyRoadmap/View/PublicTransportStepView.swift
  NavitiaSDKUITests/Scenes/ShowJourneyRoadmap/ShowJourneyRoadmapPresenterTests.swift
Labels: CHANGES MADE 😎

#304 Feature/sdk 1174
  NavitiaSDKUI.xcodeproj/project.pbxproj
  NavitiaSDKUI/Framedation/Extension/UILabel+Extension.swift
  NavitiaSDKUI/Framedation/Models/JourneysRequest.swift
  NavitiaSDKUI/Framedation/Models/PricedTicket.swift
  NavitiaSDKUI/Framedation/Models/PricesModel.swift
  NavitiaSDKUI/Framedation/Models/TicketInput.swift
  NavitiaSDKUI/NavitiaSDKUIConfig.swift
  NavitiaSDKUI/Resources/Images.xcassets/information.imageset/Contents.json
  NavitiaSDKUI/Resources/Images.xcassets/information.imageset/information.pdf
  NavitiaSDKUI/Resources/Images.xcassets/warning.imageset/Contents.json
  NavitiaSDKUI/Resources/Images.xcassets/warning.imageset/warning.pdf
  NavitiaSDKUI/Resources/en.lproj/Localizable.strings
  NavitiaSDKUI/Resources/fr.lproj/Localizable.strings
  NavitiaSDKUI/Resources/nl-NL.lproj/Localizable.strings
  NavitiaSDKUI/Resources/nl.lproj/Localizable.strings
  NavitiaSDKUI/Scenes/Common/Frieze/FriezePresenter.swift
  NavitiaSDKUI/Scenes/Common/Frieze/FriezeView.swift
  NavitiaSDKUI/Scenes/Common/Interface/TicketPriceView.xib
  NavitiaSDKUI/Scenes/Common/TicketPriceView.swift
  NavitiaSDKUI/Scenes/FormJourney/View/TransportModeView.swift
  NavitiaSDKUI/Scenes/ListJourneys/Interface/JourneySolutionCollectionViewCell.xib
  NavitiaSDKUI/Scenes/ListJourneys/ListJourneysInteractor.swift
  NavitiaSDKUI/Scenes/ListJourneys/ListJourneysModels.swift
  NavitiaSDKUI/Scenes/ListJourneys/ListJourneysPresenter.swift
  NavitiaSDKUI/Scenes/ListJourneys/ListJourneysRouter.swift
  NavitiaSDKUI/Scenes/ListJourneys/ListJourneysViewController.swift
  NavitiaSDKUI/Scenes/ListJourneys/View/JourneySolutionCollectionViewCell.swift
  NavitiaSDKUI/Scenes/ListRidesharingOffers/ListRidesharingOffersPresenter.swift
  NavitiaSDKUI/Scenes/ShowJourneyRoadmap/Interface/BuyTicketButtonView.xib
  NavitiaSDKUI/Scenes/ShowJourneyRoadmap/Interface/InformationView.xib
  NavitiaSDKUI/Scenes/ShowJourneyRoadmap/Interface/JourneySolutionView.xib
  NavitiaSDKUI/Scenes/ShowJourneyRoadmap/Interface/PublicTransportStepView.xib
  NavitiaSDKUI/Scenes/ShowJourneyRoadmap/ShowJourneyRoadmapInteractor.swift
  NavitiaSDKUI/Scenes/ShowJourneyRoadmap/ShowJourneyRoadmapModels.swift
  NavitiaSDKUI/Scenes/ShowJourneyRoadmap/ShowJourneyRoadmapPresenter.swift
  NavitiaSDKUI/Scenes/ShowJourneyRoadmap/ShowJourneyRoadmapViewController.swift
  NavitiaSDKUI/Scenes/ShowJourneyRoadmap/View/BuyTicketButtonView.swift
  NavitiaSDKUI/Scenes/ShowJourneyRoadmap/View/InformationView.swift
  NavitiaSDKUI/Scenes/ShowJourneyRoadmap/View/JourneySolutionView.swift
  NavitiaSDKUI/Scenes/ShowJourneyRoadmap/View/PublicTransportStepView.swift
  NavitiaSDKUITests/Scenes/ShowJourneyRoadmap/ShowJourneyRoadmapPresenterTests.swift
Labels: MERGE AUTHORIZED 💪
