Repository CanalTP/NavitiaSDKUX_ios, pull requests merged in 2019-03, with the labels that each got.

#241 ✨ [SDK-648] - Improvement SearchView in List Journeys
  NavitiaSDKUI.xcodeproj/project.pbxproj
  NavitiaSDKUI/Scenes/Common/Interface/SearchView.xib
  NavitiaSDKUI/Scenes/Common/SearchView.swift
  NavitiaSDKUI/Scenes/ListJourneys/ListJourneysModels.swift
  NavitiaSDKUI/Scenes/ListJourneys/ListJourneysPresenter.swift
  NavitiaSDKUI/Scenes/ListJourneys/ListJourneysViewController.swift
  NavitiaSDKUI/Storyboard/Journey.storyboard
Labels: DO NOT MERGE! ☠️, QA VALIDATION 😈

#240 🐛 [SDK-638] - Improvement map view
  NavitiaSDKUI/Scenes/Common/CustomAnnotation.swift
  NavitiaSDKUI/Scenes/ShowJourneyRoadmap/JourneyPathOverlays.swift
  NavitiaSDKUI/Scenes/ShowJourneyRoadmap/ShowJourneyRoadmapInteractor.swift
  NavitiaSDKUI/Scenes/ShowJourneyRoadmap/ShowJourneyRoadmapModels.swift
  NavitiaSDKUI/Scenes/ShowJourneyRoadmap/ShowJourneyRoadmapPresenter.swift
  NavitiaSDKUI/Scenes/ShowJourneyRoadmap/ShowJourneyRoadmapViewController.swift
Labels: REVIEW REQUIRED! 👀

#242 🐛 [SDK-649] - Fix shadow
  NavitiaSDKUI/Framedation/Extension/UIView+Extension.swift
  NavitiaSDKUI/Scenes/Common/Scroll/SlidingScrollView.swift
  NavitiaSDKUI/Scenes/ListJourneys/View/JourneyEmptySolutionCollectionViewCell.swift
  NavitiaSDKUI/Scenes/ListJourneys/View/JourneySolutionCollectionViewCell.swift
  NavitiaSDKUI/Scenes/ListJourneys/View/JourneySolutionLoadCollectionViewCell.swift
  NavitiaSDKUI/Scenes/ListJourneys/View/RidesharingInformationCollectionViewCell.swift
  NavitiaSDKUI/Scenes/ListRidesharingOffers/View/RidesharingOfferCollectionViewCell.swift
  NavitiaSDKUI/Scenes/ShowJourneyRoadmap/ShowJourneyRoadmapViewController.swift
  NavitiaSDKUI/Scenes/ShowJourneyRoadmap/View/DepartureArrivalStepView.swift
  NavitiaSDKUI/Scenes/ShowJourneyRoadmap/View/EmissionView.swift
  NavitiaSDKUI/Scenes/ShowJourneyRoadmap/View/PublicTransportStepView.swift
  NavitiaSDKUI/Scenes/ShowJourneyRoadmap/View/RidesharingView.swift
  NavitiaSDKUI/Scenes/ShowJourneyRoadmap/View/StepView.swift
Labels: QA VALIDATION 😈

#246 [SDK-800] - Text color for transport view
  Example/NavitiaSDKUI-Example.xcodeproj/project.pbxproj
  NavitiaSDKUI/Scenes/Common/Frieze/FriezePresenter.swift
  NavitiaSDKUI/Scenes/Common/Frieze/FriezeSectionView.swift
  NavitiaSDKUI/Scenes/Common/Frieze/FriezeView.swift
  NavitiaSDKUI/Scenes/ShowJourneyRoadmap/ShowJourneyRoadmapModels.swift
  NavitiaSDKUI/Scenes/ShowJourneyRoadmap/ShowJourneyRoadmapPresenter.swift
  NavitiaSDKUI/Scenes/ShowJourneyRoadmap/ShowJourneyRoadmapViewController.swift
  NavitiaSDKUI/Scenes/ShowJourneyRoadmap/View/PublicTransportStepView.swift
Labels: MERGE AUTHORIZED 💪

#249 🐛 [SDK-827] - Fix bug
  NavitiaSDKUI/Lib/NavitiaSDK/Models/Place.swift
  NavitiaSDKUI/Scenes/Common/Interface/SearchView.xib
  NavitiaSDKUI/Scenes/Common/SearchView.swift
  NavitiaSDKUI/Scenes/ListPlaces/ListPlacesInteractor.swift
  NavitiaSDKUI/Scenes/ListPlaces/ListPlacesModels.swift
  NavitiaSDKUI/Scenes/ListPlaces/ListPlacesPresenter.swift
  NavitiaSDKUI/Scenes/ListPlaces/ListPlacesViewController.swift
  NavitiaSDKUI/Scenes/ListPlaces/View/PlacesTableViewCell.swift
  NavitiaSDKUI/Workers/NavitiaWorker.swift
Labels: MERGE AUTHORIZED 💪

#248 🚀 Release 1.9.0
  Example/NavitiaSDKUI-Example.xcodeproj/project.pbxproj
  Example/NavitiaSDKUI-Example.xcodeproj/xcshareddata/xcschemes/NavitiaSDKUI-Example.xcscheme
  Example/Podfile.lock
  NavitiaSDKUI.podspec
  NavitiaSDKUI.xcodeproj/project.pbxproj
  NavitiaSDKUI/Framedation/Extension/UIPanGestureRecognizer+Extension.swift
  NavitiaSDKUI/Framedation/Extension/UIView+Extension.swift
  NavitiaSDKUI/Info.plist
  NavitiaSDKUI/Scenes/Common/AlertViewController.swift
  NavitiaSDKUI/Scenes/Common/CustomAnnotation.swift
  NavitiaSDKUI/Scenes/Common/Frieze/FriezePresenter.swift
  NavitiaSDKUI/Scenes/Common/Frieze/FriezeSectionView.swift
  NavitiaSDKUI/Scenes/Common/Frieze/FriezeView.swift
  NavitiaSDKUI/Scenes/Common/Interface/SearchView.xib
  NavitiaSDKUI/Scenes/Common/Interface/StationsView.xib
  NavitiaSDKUI/Scenes/Common/Scroll/SlidingScrollView.swift
  NavitiaSDKUI/Scenes/Common/Scroll/StackScrollView.swift
  NavitiaSDKUI/Scenes/Common/SearchView.swift
  NavitiaSDKUI/Scenes/Common/StationsView.swift
  NavitiaSDKUI/Scenes/ListJourneys/Interface/JourneyEmptySolutionCollectionViewCell.xib
  NavitiaSDKUI/Scenes/ListJourneys/Interface/RidesharingInformationCollectionViewCell.xib
  NavitiaSDKUI/Scenes/ListJourneys/ListJourneysModels.swift
  NavitiaSDKUI/Scenes/ListJourneys/ListJourneysPresenter.swift
  NavitiaSDKUI/Scenes/ListJourneys/ListJourneysViewController.swift
  NavitiaSDKUI/Scenes/ListJourneys/View/JourneyEmptySolutionCollectionViewCell.swift
  NavitiaSDKUI/Scenes/ListJourneys/View/JourneyHeaderCollectionReusableView.swift
  NavitiaSDKUI/Scenes/ListJourneys/View/JourneySolutionCollectionViewCell.swift
  NavitiaSDKUI/Scenes/ListJourneys/View/JourneySolutionLoadCollectionViewCell.swift
  NavitiaSDKUI/Scenes/ListJourneys/View/RidesharingInformationCollectionViewCell.swift
  NavitiaSDKUI/Scenes/ListRidesharingOffers/View/RidesharingOfferCollectionViewCell.swift
  NavitiaSDKUI/Scenes/ShowJourneyRoadmap/Interface/JourneySolutionView.xib
  NavitiaSDKUI/Scenes/ShowJourneyRoadmap/JourneyPathOverlays.swift
  NavitiaSDKUI/Scenes/ShowJourneyRoadmap/ShowJourneyRoadmapInteractor.swift
  NavitiaSDKUI/Scenes/ShowJourneyRoadmap/ShowJourneyRoadmapModels.swift
  NavitiaSDKUI/Scenes/ShowJourneyRoadmap/ShowJourneyRoadmapPresenter.swift
  NavitiaSDKUI/Scenes/ShowJourneyRoadmap/ShowJourneyRoadmapViewController.swift
  NavitiaSDKUI/Scenes/ShowJourneyRoadmap/View/DepartureArrivalStepView.swift
  NavitiaSDKUI/Scenes/ShowJourneyRoadmap/View/EmissionView.swift
  NavitiaSDKUI/Scenes/ShowJourneyRoadmap/View/JourneySolutionView.swift
  NavitiaSDKUI/Scenes/ShowJourneyRoadmap/View/PublicTransportStepView.swift
  NavitiaSDKUI/Scenes/ShowJourneyRoadmap/View/RidesharingView.swift
  NavitiaSDKUI/Scenes/ShowJourneyRoadmap/View/StepView.swift
  NavitiaSDKUI/Storyboard/Journey.storyboard
Labels: MERGE AUTHORIZED 💪, REVIEW REQUIRED! 👀
