Repository CanalTP/NavitiaSDKUX_ios, pull requests merged in 2019-08, with the labels that each got.

#276 Line image, black border, black text, white background if not given b…
  Example/NavitiaSDKUI-Example.xcodeproj/project.pbxproj
  NavitiaSDKUI/Framedation/Extension/UIColor+Extension.swift
  NavitiaSDKUI/Scenes/Common/Frieze/FriezePresenter.swift
  NavitiaSDKUI/Scenes/Common/Frieze/FriezeSectionView.swift
  NavitiaSDKUI/Scenes/Common/Frieze/FriezeView.swift
  NavitiaSDKUI/Scenes/ShowJourneyRoadmap/View/PublicTransportStepView.swift
Labels: QA VALIDATION 😈, REVIEW IN PROGRESS ⏱

#277 Feature/sdk 950
  Example/NavitiaSDKUI-Example.xcodeproj/project.pbxproj
  Example/NavitiaSDKUI-Example/AppDelegate.swift
  Example/NavitiaSDKUI-Example/Assets.xcassets/A pied.imageset/A pied.png
  Example/NavitiaSDKUI-Example/Assets.xcassets/A pied.imageset/Contents.json
  Example/NavitiaSDKUI-Example/Assets.xcassets/Bus.imageset/Bus.png
  Example/NavitiaSDKUI-Example/Assets.xcassets/Bus.imageset/Contents.json
  Example/NavitiaSDKUI-Example/Assets.xcassets/Metro.imageset/Contents.json
  Example/NavitiaSDKUI-Example/Assets.xcassets/Metro.imageset/Metro.png
  Example/NavitiaSDKUI-Example/Assets.xcassets/Taxi.imageset/Contents.json
  Example/NavitiaSDKUI-Example/Assets.xcassets/Taxi.imageset/Taxi.png
  Example/NavitiaSDKUI-Example/Assets.xcassets/Train.imageset/Contents.json
  Example/NavitiaSDKUI-Example/Assets.xcassets/Train.imageset/Train.png
  Example/NavitiaSDKUI-Example/Assets.xcassets/Velo.imageset/Contents.json
  Example/NavitiaSDKUI-Example/Assets.xcassets/Velo.imageset/Velo.png
  Example/NavitiaSDKUI-Example/Assets.xcassets/Voiture.imageset/Contents.json
  Example/NavitiaSDKUI-Example/Assets.xcassets/Voiture.imageset/Voiture.png
  Example/NavitiaSDKUI-Example/Assets.xcassets/compass.imageset/Contents.json
  Example/NavitiaSDKUI-Example/Assets.xcassets/compass.imageset/compass.png
  Example/NavitiaSDKUI-Example/Assets.xcassets/placeholder.imageset/Contents.json
  Example/NavitiaSDKUI-Example/Assets.xcassets/placeholder.imageset/placeholder.png
  Example/NavitiaSDKUI-Example/ConfigurationViewController.swift
  Example/Podfile.lock
  NavitiaSDKUI/Framedation/Models/ModeButtonModel.swift
  NavitiaSDKUI/NavitiaSDKUIConfig.swift
  NavitiaSDKUI/Scenes/Common/Interface/SearchView.xib
  NavitiaSDKUI/Scenes/Common/SearchView.swift
  NavitiaSDKUI/Scenes/FormJourney/FormJourneyPresenter.swift
  NavitiaSDKUI/Scenes/FormJourney/View/TransportModeButton.swift
  NavitiaSDKUI/Scenes/FormJourney/View/TransportModeView.swift
Labels: CHANGES MADE 😎

#278 Fix/sdk 1143
  Example/NavitiaSDKUI-Example.xcodeproj/project.pbxproj
  Example/NavitiaSDKUI-Example/ConfigurationViewController.swift
  NavitiaSDKUI/Framedation/Extension/UIColor+Extension.swift
  NavitiaSDKUI/Framedation/Extension/UIViewController+Extension.swift
  NavitiaSDKUI/NavitiaSDKUIConfig.swift
  NavitiaSDKUI/Scenes/Common/Frieze/FriezeView.swift
  NavitiaSDKUI/Scenes/FormJourney/FormJourneyViewController.swift
  NavitiaSDKUI/Scenes/ListJourneys/ListJourneysViewController.swift
  NavitiaSDKUI/Scenes/ListPlaces/ListPlacesViewController.swift
  NavitiaSDKUI/Scenes/ListRidesharingOffers/ListRidesharingOffersViewController.swift
  NavitiaSDKUI/Scenes/ShowJourneyRoadmap/ShowJourneyRoadmapViewController.swift
Labels: CHANGES MADE 😎

#283 🎨 Add missing icons and refactor some code
  NavitiaSDKUI/Framedation/Models/ModeButtonModel.swift
  NavitiaSDKUI/NavitiaSDKUIConfig.swift
  NavitiaSDKUI/Scenes/Common/SearchView.swift
  NavitiaSDKUI/Scenes/FormJourney/View/TransportModeButton.swift
  README.md
Labels: REVIEW REQUIRED! 👀

#284 🐛 Add administrative_region to autocomplete addresses
  NavitiaSDKUI/Scenes/ListPlaces/ListPlacesModels.swift
  NavitiaSDKUI/Scenes/ListPlaces/ListPlacesViewController.swift
  NavitiaSDKUI/Scenes/ListPlaces/View/PlacesTableViewCell.swift
Labels: MERGE AUTHORIZED 💪

#285 🐛 Fix color contrast method
  .gitignore
  Example/NavitiaSDKUI-Example/AppDelegate.swift
  Example/Podfile.lock
  NavitiaSDKUI/Framedation/Extension/UIColor+Extension.swift
Labels: MERGE AUTHORIZED 💪

#286 🐛 Fix color luminance computing method
  NavitiaSDKUI/Framedation/Extension/UIColor+Extension.swift
Labels: MERGE AUTHORIZED 💪

#287 request layout if need in viewDidAppear before starting animation
  NavitiaSDKUI.xcodeproj/xcshareddata/xcschemes/NavitiaSDKUI.xcscheme
  NavitiaSDKUI/Scenes/ShowJourneyRoadmap/ShowJourneyRoadmapViewController.swift
Labels: REVIEW REQUIRED! 👀
