Repository CanalTP/NavitiaSDKUX_ios, pull requests merged in 2019-11, with the labels that each got.

#336 Handle direct path mode
  NavitiaSDKUI/Framedation/Models/JourneysRequest.swift
Labels: CHANGES MADE 😎

#338 🐛 Fix decoding coordinates, add address sections support
  NavitiaSDKUI/Lib/NavitiaSDK/Models/SectionGeoJsonSchema.swift
  NavitiaSDKUI/Scenes/ShowJourneyRoadmap/ShowJourneyRoadmapPresenter.swift
  NavitiaSDKUI/Scenes/ShowJourneyRoadmap/ShowJourneyRoadmapViewController.swift
  NavitiaSDKUI/Scenes/Util/Icons.swift
Labels: MERGE AUTHORIZED 💪

#339 PMR gesture
  NavitiaSDKUI/Scenes/FormJourney/FormJourneyViewController.swift
Labels: MERGE AUTHORIZED 💪

#341 Remove bike when PMR is activated
  NavitiaSDKUI/Scenes/FormJourney/FormJourneyViewController.swift
  NavitiaSDKUI/Scenes/ListJourneys/ListJourneysViewController.swift
Labels: MERGE AUTHORIZED 💪

#342 Fix the way to handle ticket's
  NavitiaSDKUI/Scenes/ListJourneys/ListJourneysPresenter.swift
Labels: REVIEW REQUIRED! 👀
