Repository CanalTP/NavitiaSDKUX_ios, pull requests merged in 2019-07, with the labels that each got.

#264 🐛 Fix : No more condition to display custom clear button
  Example/NavitiaSDKUI-Example.xcodeproj/project.pbxproj
  NavitiaSDKUI/Scenes/Common/SearchView.swift
Labels: QA VALIDATION 😈

#269 [form] Define minimum date
  NavitiaSDKUI/Scenes/FormJourney/View/DateFormView.swift
Labels: MERGE AUTHORIZED 💪

#268 🧚🏼‍♀️ Fix missing coverages
  Example/NavitiaSDKUI-Example/CoverageViewController.swift
Labels: MERGE AUTHORIZED 💪

#271 fix sliding view after rotation
  NavitiaSDKUI/Scenes/Common/Scroll/SlidingScrollView.swift
Labels: MERGE AUTHORIZED 💪

#270 fix textfield constraint mistake
  NavitiaSDKUI/Scenes/Common/Interface/SearchView.xib
  NavitiaSDKUI/Scenes/Common/SearchView.swift
  NavitiaSDKUI/Scenes/ListPlaces/ListPlacesViewController.swift
Labels: MERGE AUTHORIZED 💪

#274 Fix/sdk 1106
  Example/NavitiaSDKUI-Example.xcodeproj/project.pbxproj
  Example/NavitiaSDKUI-Example/Base.lproj/Main.storyboard
  Example/NavitiaSDKUI-Example/ConfigurationViewController.swift
  Example/NavitiaSDKUI-Example/fr.lproj/Main.strings
  NavitiaSDKUI.xcodeproj/project.pbxproj
  NavitiaSDKUI/Scenes/ListPlaces/ListPlacesViewController.swift
  NavitiaSDKUI/Scenes/ShowJourneyRoadmap/ShowJourneyRoadmapPresenter.swift
Labels: MERGE AUTHORIZED 💪

#275 🧚🏼‍♀️ Fix BSS mode
  NavitiaSDKUI/Scenes/Util/Icons.swift
  NavitiaSDKUI/Workers/NavitiaWorker.swift
  ci/Build
Labels: HIGH PRIORITY ⚠️, MERGE AUTHORIZED 💪
